### ISSUE TITLE
ImportError: No module named 'helpers'

### ISSUE THREAD

**Issue by timlichen** [blockchain-certificates/cert-tools#17]
running the command 
`create-certificate-template -c conf.ini` 
gives the error 
`ImportError: No module named 'helpers'`

I think there was an issue with my virtual machine and how it was handling my site-packages.

**Comment by kimdhamilton** [comment]
Thanks @timlichen -- this was a bug in an earlier version, so it's possible you had a stale version. Glad it's working!
