### ISSUE TITLE
badge Id and certificate Id

### ISSUE THREAD

**Issue by praveen5exceptions** [blockchain-certificates/cert-tools#25]
What are difference in Badge ID and Certificate Id?

**Comment by kimdhamilton** [comment]
See the Open Bages docs:
- Badge id is defined here: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#BadgeClass
- Certificate id: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#Assertion
